### ISSUE TITLE
Annotation helper sometimes needs trailing spaces to make mouse-over tooltips work 

### ISSUE THREAD

**Issue by kupietz** [KorAP/Kalamar#193]
It seems to be necessary to add trailing spaces to POS tags like here:

https://github.com/KorAP/Kalamar/blob/9d82690497d616400f4de3955fcc2f4e88669d69/dev/js/src/hint/foundries/stts.js#L6

Mouse-over tooltips currently do now work for NKJP and UD annoations as they don´t have these traling spaces.

**Comment by Akron** [comment]
Yes, the trailing spaces indicate the end of the annotation term - POS have no "values", only "keys" in our annotation terminology of `foundry/layer=key:value`. So key-Annotations require an endmarker, which is the space symbol. Using the space symbol has the additional advantage to introduce a space following the annotation when added to the input field. So the user can directly add operators or brackets following that. NKJP is fixed in Gerrit.
