### ISSUE TITLE
Make corpus statistics reloadable when VC changes

### ISSUE THREAD

**Issue by Akron** [KorAP/Kalamar#66]
Currently, the statistics view is always refering to the state of the VC the moment the statistics button was pressed. When the VC changes, the statistics view needs to be closed and then reopened to reload the statistics results.

I think it's important to either always have the correct statistics in view, or to inform the user, when the data does not reflect the VC.

The first approach can be realized, by
- Always reload the statistics, whenever the VC is updated. This is unfortunately extremely slow.
- Close the statistics, whenever the VC is updated. This may be problematic, when the user wants to alter the VC based on the statistics (so he needs to see the numbers when preparing/comparing the VC).

I would suggest to take the information route and

- Add a little marker to the statistics button or as part of the statistics view, indicating the statistics is old, whenever the VC is updated. In case the statistics are old, the user can click on the statistics button again, to update the values. The marker will then vanish.

This requires a method to inform the statistics view about any (meaningful) changes in the VC object. A possible approach would be to introduce an event.

**Comment by hebasta** [comment]
We had quite a debate about the current UI-design of this functionality:
Is it is more intuitive, if a reload button appears right next to the corpus statistic, or should the reload functionality not be shown through an additional button, but be signalized through disabling and enabling the existant statistic-button?

We decided for an additional reload button, because we have to consider, that we have more vc-views in the future and might order them in horizontal tabs in the vc-panel. Therefore the statistic-button should not be disabled.
